
use Talbook;
insert into Service (skills)
values ("Dynamics control"),
("Tapping (guitar)"),
("Musical interpretation"),
("(Brass) Mute use and effects"),
("(Plucked Strings) Alternate tunings"),
("Vocal agility"),
("Beatboxing"),
("(Percussion) Mallet technique"),
("(Percussion) Coordination and limb independence"),
("(Woodwind) Embouchure control"),
("Pop phrasing"),
("DJing"),
("(Vocal) Harmony singing"),
("Stage presence"),
("Jazz improvisation"),
("(String) Double stops"),
("Sight-singing"),
("Transcribing"),
("Intonation"),
("Pedaling (for piano)"),
("Improvisation"),
("Slide technique"),
("(Plucked Strings) Chord voicings and inversions"),
("Mastering"),
("(General) Music theory knowledge"),
("Harmonic analysis"),
("Mixing"),
("(General) Phrasing and articulation"),
("(String) Shifting between positions"),
("Orchestration"),
("(Brass) Range extension"),
("(Keyboard) Improvisation"),
("(World/Folk) Hand techniques"),
("Chord voicing"),
("(World/Folk) Traditional rhythmic patterns"),
("(Vocal) Breath control"),
("(String) Harmonics"),
("(General) Playing in ensemble/band/orchestra"),
("(Woodwind) Vibrato"),
("Rock rhythm"),
("(Plucked Strings) Looping"),
("Timbre control"),
("Counterpoint writing"),
("(Keyboard) Hand independence"),
("(Brass) Breath support and control"),
("(Plucked Strings) Tapping and slapping"),
("Arranging"),
("(Keyboard) Synth programming"),
("(Plucked Strings) Hammer-ons and pull-offs"),
("MIDI programming"),
("Music notation"),
("Songwriting"),
("Hybrid picking"),
("Double stops"),
("(Brass) Articulation (tonguing, slurring)"),
("(World/Folk) Instrument-specific techniques"),
("(General) Stage performance skills"),
("Sight-reading"),
("(General) Memorization"),
("Harmonics playing"),
("(Brass) Lip control/embouchure"),
("(Plucked Strings) Fingerpicking and flatpicking"),
("Arpeggio execution"),
("Studio recording"),
("Sound design"),
("Voice blending"),
("(String) Pizzicato"),
("Instrument tuning"),
("(Plucked Strings) Barre chords"),
("Music theory knowledge"),
("Hammer-ons & pull-offs"),
("(Percussion) Sight-reading rhythms"),
("Vibrato"),
("Audio editing"),
("(Percussion) Timekeeping and groove"),
("(Keyboard) Pedal usage"),
("Composition"),
("(Vocal) Pitch accuracy"),
("Key signature fluency"),
("Tempo control"),
("Synth programming"),
("(Percussion) Rudiments (e.g., paradiddles, rolls)"),
("Rhythm accuracy"),
("(Vocal) Vibrato and runs"),
("Meter changes"),
("Classical technique"),
("(General) Dynamics control"),
("(Woodwind) Finger dexterity"),
("(World/Folk) Cultural style interpretation"),
("(Plucked Strings) Slides and bends"),
("Breath control"),
("Live performance"),
("Falsetto control"),
("(General) Genre versatility"),
("(Percussion) Tuning drums"),
("(General) Ear training / aural skills"),
("DAW operation"),
("Expressive timing"),
("(Brass) Valve or slide technique"),
("Finger independence"),
("Foley creation"),
("(Vocal) Microphone technique"),
("Range extension"),
("Embouchure (for winds/brass)"),
("Breath support"),
("Sampling"),
("(Vocal) Diction and enunciation"),
("Palm muting"),
("(Keyboard) Scale and arpeggio fluency"),
("(General) Tuning and intonation"),
("(String) Vibrato"),
("Rapping"),
("(Vocal) Vocal range extension"),
("Looping"),
("Bowing techniques (for strings)"),
(""),
("Modulation control"),
("(Percussion) Stick control and grip techniques"),
("Music production"),
("(Keyboard) Voicing and dynamics control"),
("Percussive playing"),
("Muting technique"),
("Lyric writing"),
("(General) Sight-reading"),
("(Vocal) Style adaptation"),
("(String) Finger positioning"),
("Fingerpicking (guitar)"),
("Repertoire building"),
("Whammy bar use"),
("Tremolo picking"),
("Two-hand tapping"),
("Diction"),
("Ensemble playing"),
("(Woodwind) Circular breathing"),
("Conducting"),
("Articulation"),
("(Keyboard) Sight-reading multiple staves"),
("(Percussion) Rhythm precision"),
("Accent placement"),
("(Woodwind) Articulation (tonguing, flutter tonguing)"),
("(General) Rhythm accuracy"),
("Cross-string picking"),
("Polyrhythm ability"),
("(General) Transposition"),
("(String) Bowing techniques (e.g., spiccato, legato, staccato)"),
("Groove maintenance"),
("(Woodwind) Breath support"),
("Ear training"),
("Score reading"),
("Phrasing"),
("(Woodwind) Overblowing and harmonic notes"),
("Scale fluency"),
("(General) Composition and arrangement"),
("Strumming patterns"),
("Hand coordination"),
("(General) Improvisation");